-- ============================================================
-- DeutschPilot — Firebase UID Architecture Fix
-- Run this ONCE in Supabase Dashboard → SQL Editor → New query
--
-- Design:
--   profiles.id         = uuid  (auto-generated by Supabase — never changes)
--   profiles.firebase_uid = text UNIQUE  (Firebase UID, e.g. "UQWhfawlAy...")
--   live_classes.teacher_id  = uuid → profiles.id
--   class_enrollments.student_id = uuid → profiles.id
--
-- DO NOT insert Firebase UIDs into profiles.id.
-- DO NOT use auth.uid() anywhere — this app uses Firebase Auth.
-- All auth verified server-side via Firebase Admin SDK.
-- All DB writes use Supabase service-role client (bypasses RLS).
-- ============================================================

-- ============================================================
-- STEP 1 — Fix profiles table
-- ============================================================

-- Drop the broken FK to auth.users (Firebase ≠ Supabase Auth)
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- Add firebase_uid as the text lookup key
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS firebase_uid text;

-- Make it unique (allow NULL temporarily so existing rows don't break)
DROP INDEX IF EXISTS idx_profiles_firebase_uid;
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_firebase_uid
  ON public.profiles(firebase_uid)
  WHERE firebase_uid IS NOT NULL;

-- Drop all stale auth.uid() policies — useless for Firebase Auth
DROP POLICY IF EXISTS profiles_owner        ON public.profiles;
DROP POLICY IF EXISTS profiles_admin_select ON public.profiles;
DROP POLICY IF EXISTS "profiles_service_role_all" ON public.profiles;
DROP POLICY IF EXISTS profiles_open         ON public.profiles;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_open ON public.profiles
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- STEP 2 — Fix live_classes.teacher_id (text → uuid → profiles.id)
-- Safe: uses DO block to check for existing data first
-- ============================================================

DO $$
BEGIN
  -- Only migrate if table is empty (no real data to lose)
  IF (SELECT COUNT(*) FROM public.live_classes) = 0 THEN
    -- Drop old text teacher_id and recreate as uuid FK
    ALTER TABLE public.live_classes DROP COLUMN IF EXISTS teacher_id;
    ALTER TABLE public.live_classes
      ADD COLUMN teacher_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
    DROP INDEX IF EXISTS idx_live_classes_teacher;
    CREATE INDEX idx_live_classes_teacher ON public.live_classes(teacher_id);
    RAISE NOTICE 'live_classes.teacher_id converted to uuid FK → profiles.id';
  ELSE
    -- Table has data — add a new column alongside, manual backfill needed
    ALTER TABLE public.live_classes
      ADD COLUMN IF NOT EXISTS teacher_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
    RAISE NOTICE 'live_classes has rows — added teacher_profile_id (uuid). Backfill teacher_profile_id manually, then swap columns.';
  END IF;
END $$;

DROP POLICY IF EXISTS live_classes_open ON public.live_classes;
ALTER TABLE public.live_classes ENABLE ROW LEVEL SECURITY;
CREATE POLICY live_classes_open ON public.live_classes
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- STEP 3 — Fix class_enrollments.student_id (text → uuid → profiles.id)
-- ============================================================

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.class_enrollments) = 0 THEN
    ALTER TABLE public.class_enrollments DROP COLUMN IF EXISTS student_id;
    ALTER TABLE public.class_enrollments
      ADD COLUMN student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE;
    -- Restore the unique constraint
    ALTER TABLE public.class_enrollments
      DROP CONSTRAINT IF EXISTS class_enrollments_class_id_student_id_key;
    ALTER TABLE public.class_enrollments
      ADD CONSTRAINT class_enrollments_class_id_student_id_key UNIQUE (class_id, student_id);
    DROP INDEX IF EXISTS idx_enrollments_student;
    CREATE INDEX idx_enrollments_student ON public.class_enrollments(student_id);
    RAISE NOTICE 'class_enrollments.student_id converted to uuid FK → profiles.id';
  ELSE
    ALTER TABLE public.class_enrollments
      ADD COLUMN IF NOT EXISTS student_profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE;
    RAISE NOTICE 'class_enrollments has rows — added student_profile_id. Backfill manually.';
  END IF;
END $$;

DROP POLICY IF EXISTS enrollments_open ON public.class_enrollments;
ALTER TABLE public.class_enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY enrollments_open ON public.class_enrollments
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- STEP 4 — Fix student_room_progress and student_task_progress
-- (user_id: uuid → text for Firebase UID, no profiles FK needed)
-- ============================================================

ALTER TABLE public.student_room_progress
  DROP CONSTRAINT IF EXISTS student_room_progress_user_id_fkey;
ALTER TABLE public.student_room_progress
  ALTER COLUMN user_id TYPE text USING user_id::text;

DROP POLICY IF EXISTS srp_owner  ON public.student_room_progress;
DROP POLICY IF EXISTS srp_admin  ON public.student_room_progress;
DROP POLICY IF EXISTS srp_open   ON public.student_room_progress;
ALTER TABLE public.student_room_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY srp_open ON public.student_room_progress
  FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.student_task_progress
  DROP CONSTRAINT IF EXISTS student_task_progress_user_id_fkey;
ALTER TABLE public.student_task_progress
  ALTER COLUMN user_id TYPE text USING user_id::text;

DROP POLICY IF EXISTS stp_owner  ON public.student_task_progress;
DROP POLICY IF EXISTS stp_admin  ON public.student_task_progress;
DROP POLICY IF EXISTS stp_open   ON public.student_task_progress;
ALTER TABLE public.student_task_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY stp_open ON public.student_task_progress
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- STEP 5 — Other tables (learning_rooms, room_tasks, etc.)
-- ============================================================

ALTER TABLE public.learning_rooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS learning_rooms_select_auth ON public.learning_rooms;
DROP POLICY IF EXISTS learning_rooms_read        ON public.learning_rooms;
CREATE POLICY learning_rooms_read ON public.learning_rooms FOR SELECT USING (true);

ALTER TABLE public.room_tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS room_tasks_select_auth ON public.room_tasks;
DROP POLICY IF EXISTS room_tasks_read        ON public.room_tasks;
CREATE POLICY room_tasks_read ON public.room_tasks FOR SELECT USING (true);

-- teacher_profiles keeps text user_id (Firebase UID) — separate from profiles table
DO $$ BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema='public' AND table_name='teacher_profiles') THEN
    ALTER TABLE public.teacher_profiles ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DROP POLICY IF EXISTS teacher_profiles_open ON public.teacher_profiles;
CREATE POLICY teacher_profiles_open ON public.teacher_profiles
  FOR ALL USING (true) WITH CHECK (true);

DO $$ BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema='public' AND table_name='ai_trainer_usage') THEN
    ALTER TABLE public.ai_trainer_usage ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DROP POLICY IF EXISTS ai_trainer_usage_open ON public.ai_trainer_usage;
CREATE POLICY ai_trainer_usage_open ON public.ai_trainer_usage
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- VERIFY — run this SELECT after the migration
-- ============================================================
SELECT
  c.table_name,
  c.column_name,
  c.data_type,
  c.is_nullable
FROM information_schema.columns c
WHERE c.table_schema = 'public'
  AND (
    (c.table_name = 'profiles'           AND c.column_name IN ('id','firebase_uid','role'))
    OR (c.table_name = 'live_classes'    AND c.column_name IN ('teacher_id','teacher_profile_id'))
    OR (c.table_name = 'class_enrollments' AND c.column_name IN ('student_id','student_profile_id'))
  )
ORDER BY c.table_name, c.column_name;
