-- ============================================================
-- DeutschPilot – Driving Theory (Klasse B) starter set, 30 questions
-- Original prep questions covering well-established German traffic
-- law topics. NOT verbatim official Fragenkatalog questions — no
-- licensed source for that dataset was available. Additive only.
-- ============================================================

INSERT INTO public.driving_theory_questions
  (license_class, category, question_de, question_en, options_de, options_en, correct_answer_de, correct_answer_en, explanation_de, explanation_en, order_index)
VALUES

-- Alkohol & Drogen
('B','Alkohol & Drogen',
 'Wie hoch ist die allgemeine Promillegrenze für Autofahrer in Deutschland?',
 'What is the general blood alcohol limit for drivers in Germany?',
 '["0,5‰","0,8‰","1,1‰","0,3‰"]'::jsonb,
 '["0.5‰","0.8‰","1.1‰","0.3‰"]'::jsonb,
 '0,5‰','0.5‰',
 'Ab 0,5‰ liegt eine Ordnungswidrigkeit vor, ab 1,1‰ eine Straftat (absolute Fahruntüchtigkeit).',
 'From 0.5‰ it is an administrative offense; from 1.1‰ it becomes a criminal offense (absolute unfitness to drive).',
 1),

('B','Alkohol & Drogen',
 'Welche Promillegrenze gilt für Fahranfänger in der Probezeit und für Fahrer unter 21 Jahren?',
 'What blood alcohol limit applies to new drivers in the probationary period and drivers under 21?',
 '["0,0‰","0,5‰","0,3‰","0,8‰"]'::jsonb,
 '["0.0‰","0.5‰","0.3‰","0.8‰"]'::jsonb,
 '0,0‰','0.0‰',
 'Für diese Gruppe gilt ein absolutes Alkoholverbot am Steuer.',
 'This group is subject to an absolute zero-alcohol rule while driving.',
 2),

('B','Alkohol & Drogen',
 'Ab welchem Wert liegt "absolute Fahruntüchtigkeit" vor — eine Straftat unabhängig von erkennbaren Ausfallerscheinungen?',
 'At what level is "absolute unfitness to drive" reached — a criminal offense regardless of visible impairment?',
 '["1,1‰","0,5‰","0,8‰","1,6‰"]'::jsonb,
 '["1.1‰","0.5‰","0.8‰","1.6‰"]'::jsonb,
 '1,1‰','1.1‰',
 'Ab 1,1‰ wird gesetzlich von absoluter Fahruntüchtigkeit ausgegangen.',
 'From 1.1‰, the law presumes absolute unfitness to drive.',
 3),

('B','Alkohol & Drogen',
 'Auch unter 0,5‰ kann eine Straftat vorliegen, wenn...',
 'Even under 0.5‰, a criminal offense can occur if...',
 '["erkennbare Ausfallerscheinungen vorliegen (z. B. Schlangenlinien fahren)","das Auto neu ist","es regnet","laute Musik läuft"]'::jsonb,
 '["there are visible signs of impairment (e.g. swerving)","the car is new","it is raining","loud music is playing"]'::jsonb,
 'erkennbare Ausfallerscheinungen vorliegen (z. B. Schlangenlinien fahren)',
 'there are visible signs of impairment (e.g. swerving)',
 'Schon ab 0,3‰ kann bei erkennbaren Ausfallerscheinungen eine Straftat vorliegen, nicht erst ab 0,5‰.',
 'From as low as 0.3‰, visible impairment can already constitute a criminal offense, not only from 0.5‰.',
 4),

('B','Alkohol & Drogen',
 'Wie wirkt sich Alkohol typischerweise auf das Fahrverhalten aus?',
 'How does alcohol typically affect driving ability?',
 '["Er verlangsamt die Reaktionszeit und verengt das Blickfeld","Er verbessert die Konzentration","Er hat bei geringen Mengen keinen Effekt","Er verbessert die Reaktionszeit"]'::jsonb,
 '["It slows reaction time and narrows the field of vision","It improves concentration","It has no effect in small amounts","It improves reaction time"]'::jsonb,
 'Er verlangsamt die Reaktionszeit und verengt das Blickfeld',
 'It slows reaction time and narrows the field of vision',
 NULL, NULL,
 5),

-- Geschwindigkeit
('B','Geschwindigkeit',
 'Zulässige Höchstgeschwindigkeit innerorts für PKW, sofern nicht anders beschildert?',
 'Speed limit within city limits for cars, unless otherwise signed?',
 '["50 km/h","30 km/h","60 km/h","70 km/h"]'::jsonb,
 '["50 km/h","30 km/h","60 km/h","70 km/h"]'::jsonb,
 '50 km/h','50 km/h',
 NULL, NULL,
 6),

('B','Geschwindigkeit',
 'Zulässige Höchstgeschwindigkeit außerorts für PKW ohne Anhänger, sofern nicht anders beschildert?',
 'Speed limit outside built-up areas for cars without a trailer, unless otherwise signed?',
 '["100 km/h","80 km/h","120 km/h","90 km/h"]'::jsonb,
 '["100 km/h","80 km/h","120 km/h","90 km/h"]'::jsonb,
 '100 km/h','100 km/h',
 NULL, NULL,
 7),

('B','Geschwindigkeit',
 'Gibt es auf der Autobahn ein generelles Tempolimit für PKW?',
 'Is there a general speed limit for cars on the Autobahn?',
 '["Nein, aber 130 km/h ist die empfohlene Richtgeschwindigkeit","Ja, immer 120 km/h","Ja, immer 130 km/h","Nein, es gibt gar keine Empfehlung"]'::jsonb,
 '["No, but 130 km/h is the recommended (non-binding) guideline speed","Yes, always 120 km/h","Yes, always 130 km/h","No, there is no recommendation at all"]'::jsonb,
 'Nein, aber 130 km/h ist die empfohlene Richtgeschwindigkeit',
 'No, but 130 km/h is the recommended (non-binding) guideline speed',
 'Die Richtgeschwindigkeit ist eine Empfehlung, kein Bußgeld-relevantes Limit — sofern kein Schild etwas anderes vorgibt.',
 'The guideline speed is a recommendation, not a finable limit — unless a sign states otherwise.',
 8),

('B','Geschwindigkeit',
 'In einer Tempo-30-Zone gilt diese Geschwindigkeit...',
 'In a 30 km/h zone, this speed applies to...',
 '["der gesamten Zone, nicht nur einer einzelnen Straße","nur der Beschilderung selbst","nur nachts","nur LKW"]'::jsonb,
 '["the entire zone, not just one street","only the sign location itself","only at night","only trucks"]'::jsonb,
 'der gesamten Zone, nicht nur einer einzelnen Straße',
 'the entire zone, not just one street',
 NULL, NULL,
 9),

('B','Geschwindigkeit',
 'Warum sind Geschwindigkeitsbegrenzungen in Wohngebieten oft niedriger?',
 'Why are speed limits in residential areas often lower?',
 '["Zum Schutz von Fußgängern und spielenden Kindern","Weil die Straßen dort schlechter sind","Aus steuerlichen Gründen","Ohne besonderen Grund"]'::jsonb,
 '["To protect pedestrians and children playing","Because the roads are in worse condition there","For tax reasons","No particular reason"]'::jsonb,
 'Zum Schutz von Fußgängern und spielenden Kindern',
 'To protect pedestrians and children playing',
 NULL, NULL,
 10),

-- Vorfahrt & Kreisverkehr
('B','Vorfahrt & Kreisverkehr',
 'An einer Kreuzung ohne Vorfahrtsschilder gilt die Regel...',
 'At an intersection with no priority signs, the rule is...',
 '["rechts vor links","links vor rechts","wer zuerst da ist","das größere Fahrzeug hat Vorfahrt"]'::jsonb,
 '["right before left","left before right","first come, first served","the bigger vehicle has priority"]'::jsonb,
 'rechts vor links','right before left',
 NULL, NULL,
 11),

('B','Vorfahrt & Kreisverkehr',
 'Im Kreisverkehr (ohne besondere Beschilderung) haben Vorfahrt...',
 'In a roundabout (without special signage), priority belongs to...',
 '["die Fahrzeuge, die sich bereits im Kreisverkehr befinden","die einfahrenden Fahrzeuge","das schnellere Fahrzeug","es gibt keine feste Regel"]'::jsonb,
 '["vehicles already inside the roundabout","vehicles entering the roundabout","the faster vehicle","there is no fixed rule"]'::jsonb,
 'die Fahrzeuge, die sich bereits im Kreisverkehr befinden',
 'vehicles already inside the roundabout',
 NULL, NULL,
 12),

('B','Vorfahrt & Kreisverkehr',
 'Ein gelbes Rauten-Schild (auf der Spitze stehendes gelbes Viereck) bedeutet...',
 'A yellow diamond sign means...',
 '["Vorfahrtstraße","Vorfahrt gewähren","Stopp","Einbahnstraße"]'::jsonb,
 '["Priority road","Yield","Stop","One-way street"]'::jsonb,
 'Vorfahrtstraße','Priority road',
 NULL, NULL,
 13),

('B','Vorfahrt & Kreisverkehr',
 'An einem Stoppschild musst du...',
 'At a stop sign, you must...',
 '["vollständig anhalten, auch wenn kein anderes Fahrzeug zu sehen ist","nur langsamer werden","nur anhalten, wenn ein Auto kommt","hupen und weiterfahren"]'::jsonb,
 '["come to a complete stop, even if no other vehicle is visible","just slow down","only stop if another car is coming","honk and continue"]'::jsonb,
 'vollständig anhalten, auch wenn kein anderes Fahrzeug zu sehen ist',
 'come to a complete stop, even if no other vehicle is visible',
 NULL, NULL,
 14),

('B','Vorfahrt & Kreisverkehr',
 'Rettungsfahrzeuge mit Blaulicht und Martinshorn...',
 'Emergency vehicles with blue lights and siren...',
 '["haben immer Vorfahrt — du musst ihnen Platz machen","haben nur bei Rot Vorfahrt","müssen selbst auf die Vorfahrt anderer achten","haben nur außerorts Vorfahrt"]'::jsonb,
 '["always have priority — you must make way for them","only have priority at red lights","must themselves respect others'' right of way","only have priority outside built-up areas"]'::jsonb,
 'haben immer Vorfahrt — du musst ihnen Platz machen',
 'always have priority — you must make way for them',
 NULL, NULL,
 15),

-- Abstand & Bremsen
('B','Abstand & Bremsen',
 'Als Faustregel für den Sicherheitsabstand in Metern bei guten Bedingungen gilt...',
 'As a rule of thumb for the safe following distance in meters under good conditions...',
 '["halber Tacho (Geschwindigkeit ÷ 2)","doppelter Tacho","immer 50 Meter","eine Fahrzeuglänge reicht"]'::jsonb,
 '["half the speedometer reading (speed ÷ 2)","double the speedometer reading","always 50 meters","one vehicle length is enough"]'::jsonb,
 'halber Tacho (Geschwindigkeit ÷ 2)',
 'half the speedometer reading (speed ÷ 2)',
 'Bei 100 km/h also mindestens etwa 50 Meter Abstand.',
 'At 100 km/h, that means at least about 50 meters of distance.',
 16),

('B','Abstand & Bremsen',
 'Bei Nässe oder Glätte sollte der Sicherheitsabstand...',
 'In wet or icy conditions, the safe following distance should be...',
 '["deutlich vergrößert werden","gleich bleiben","verkleinert werden","spielt keine Rolle"]'::jsonb,
 '["significantly increased","kept the same","reduced","irrelevant"]'::jsonb,
 'deutlich vergrößert werden','significantly increased',
 NULL, NULL,
 17),

('B','Abstand & Bremsen',
 'Wie verändert sich der Bremsweg (bei gleicher Bremsleistung), wenn sich die Geschwindigkeit verdoppelt?',
 'How does braking distance change (at the same braking performance) if speed doubles?',
 '["Er vervierfacht sich (wächst quadratisch mit der Geschwindigkeit)","Er verdoppelt sich","Er bleibt gleich","Er halbiert sich"]'::jsonb,
 '["It quadruples (grows with the square of speed)","It doubles","It stays the same","It halves"]'::jsonb,
 'Er vervierfacht sich (wächst quadratisch mit der Geschwindigkeit)',
 'It quadruples (grows with the square of speed)',
 NULL, NULL,
 18),

('B','Abstand & Bremsen',
 'Was ist der "Reaktionsweg"?',
 'What is the "reaction distance"?',
 '["Die Strecke, die das Fahrzeug zurücklegt, bevor der Fahrer reagiert","Die Strecke nach dem Bremsen","Die Strecke bis zum nächsten Schild","Die Länge des Fahrzeugs"]'::jsonb,
 '["The distance the vehicle travels before the driver reacts","The distance after braking","The distance to the next sign","The length of the vehicle"]'::jsonb,
 'Die Strecke, die das Fahrzeug zurücklegt, bevor der Fahrer reagiert',
 'The distance the vehicle travels before the driver reacts',
 NULL, NULL,
 19),

('B','Abstand & Bremsen',
 'Warum ist ausreichender Abstand zum Vordermann wichtig?',
 'Why is keeping enough distance from the car ahead important?',
 '["Um bei einer Notbremsung rechtzeitig anhalten zu können","Aus ästhetischen Gründen","Um Kraftstoff zu sparen","Ohne besonderen Grund"]'::jsonb,
 '["To be able to stop in time during an emergency braking","For aesthetic reasons","To save fuel","No particular reason"]'::jsonb,
 'Um bei einer Notbremsung rechtzeitig anhalten zu können',
 'To be able to stop in time during an emergency braking',
 NULL, NULL,
 20),

-- Sicherheit im Auto
('B','Sicherheit im Auto',
 'Die Anschnallpflicht gilt...',
 'The seatbelt requirement applies to...',
 '["allen Sitzplätzen, an denen Gurte vorhanden sind","nur dem Fahrer","nur auf der Autobahn","nur Erwachsenen"]'::jsonb,
 '["all seats where belts are fitted","only the driver","only on the Autobahn","only adults"]'::jsonb,
 'allen Sitzplätzen, an denen Gurte vorhanden sind',
 'all seats where belts are fitted',
 NULL, NULL,
 21),

('B','Sicherheit im Auto',
 'Als grobe Regel: bis zu welchem Alter/welcher Körpergröße müssen Kinder in einem geeigneten Kindersitz/Rückhaltesystem gesichert werden?',
 'As a rough rule: up to what age/height must children be secured in an appropriate child seat/restraint system?',
 '["bis 12 Jahre oder 150 cm Körpergröße, je nachdem was zuerst eintritt","bis 6 Jahre","bis 18 Jahre","es gibt keine feste Regel"]'::jsonb,
 '["up to age 12 or 150 cm height, whichever comes first","up to age 6","up to age 18","there is no fixed rule"]'::jsonb,
 'bis 12 Jahre oder 150 cm Körpergröße, je nachdem was zuerst eintritt',
 'up to age 12 or 150 cm height, whichever comes first',
 NULL, NULL,
 22),

('B','Sicherheit im Auto',
 'Die Nutzung eines Mobiltelefons während der Fahrt ist...',
 'Using a mobile phone while driving is...',
 '["nur mit Freisprecheinrichtung erlaubt — Halten in der Hand ist verboten","komplett erlaubt","nur nachts verboten","nur außerorts verboten"]'::jsonb,
 '["only allowed hands-free — holding it in your hand is prohibited","completely allowed","only prohibited at night","only prohibited outside built-up areas"]'::jsonb,
 'nur mit Freisprecheinrichtung erlaubt — Halten in der Hand ist verboten',
 'only allowed hands-free — holding it in your hand is prohibited',
 NULL, NULL,
 23),

('B','Sicherheit im Auto',
 'Eine "situative Winterreifenpflicht" bedeutet...',
 'A "situational winter tire requirement" means...',
 '["Winterreifen sind bei winterlichen Straßenverhältnissen (Schnee, Eis, Glätte) vorgeschrieben, unabhängig vom Kalenderdatum","Winterreifen sind nur im Dezember Pflicht","Winterreifen sind nie Pflicht","Winterreifen sind ganzjährig Pflicht"]'::jsonb,
 '["Winter tires are required whenever road conditions are wintry (snow, ice, black ice), regardless of the calendar date","Winter tires are only required in December","Winter tires are never required","Winter tires are required year-round"]'::jsonb,
 'Winterreifen sind bei winterlichen Straßenverhältnissen (Schnee, Eis, Glätte) vorgeschrieben, unabhängig vom Kalenderdatum',
 'Winter tires are required whenever road conditions are wintry (snow, ice, black ice), regardless of the calendar date',
 NULL, NULL,
 24),

('B','Sicherheit im Auto',
 'Warnweste und Warndreieck im Auto sind...',
 'A warning vest and warning triangle in the car are...',
 '["gesetzlich vorgeschrieben für den Pannenfall","optional","nur für LKW Pflicht","nur im Ausland nötig"]'::jsonb,
 '["legally required for breakdown situations","optional","only mandatory for trucks","only needed abroad"]'::jsonb,
 'gesetzlich vorgeschrieben für den Pannenfall',
 'legally required for breakdown situations',
 NULL, NULL,
 25),

-- Verkehrszeichen
('B','Verkehrszeichen',
 'Ein rundes Schild mit rotem Rand und weißem Hintergrund zeigt meist...',
 'A round sign with a red border and white background usually shows...',
 '["ein Verbot","ein Gebot","eine Vorfahrt","eine Information"]'::jsonb,
 '["a prohibition","a mandatory instruction","a right of way","general information"]'::jsonb,
 'ein Verbot','a prohibition',
 NULL, NULL,
 26),

('B','Verkehrszeichen',
 'Ein blaues rundes Schild zeigt meist...',
 'A round blue sign usually shows...',
 '["ein Gebot (z. B. vorgeschriebene Fahrtrichtung)","ein Verbot","eine Gefahr","eine Vorfahrt"]'::jsonb,
 '["a mandatory instruction (e.g. a required direction of travel)","a prohibition","a hazard","a right of way"]'::jsonb,
 'ein Gebot (z. B. vorgeschriebene Fahrtrichtung)',
 'a mandatory instruction (e.g. a required direction of travel)',
 NULL, NULL,
 27),

('B','Verkehrszeichen',
 'Ein dreieckiges Schild mit rotem Rand zeigt meist...',
 'A triangular sign with a red border usually shows...',
 '["eine Gefahrenstelle","ein Verbot","eine Vorfahrtstraße","ein Parkverbot"]'::jsonb,
 '["a hazard ahead","a prohibition","a priority road","a no-parking zone"]'::jsonb,
 'eine Gefahrenstelle','a hazard ahead',
 NULL, NULL,
 28),

('B','Verkehrszeichen',
 'Das Schild "Vorfahrt gewähren" hat welche Form?',
 'What shape is the "Yield" sign?',
 '["ein auf der Spitze stehendes Dreieck","ein Kreis","ein Quadrat","ein Achteck"]'::jsonb,
 '["an inverted (point-down) triangle","a circle","a square","an octagon"]'::jsonb,
 'ein auf der Spitze stehendes Dreieck',
 'an inverted (point-down) triangle',
 NULL, NULL,
 29),

('B','Verkehrszeichen',
 'Ein achteckiges rotes Schild bedeutet...',
 'An octagonal red sign means...',
 '["Stopp — Halt!","Vorfahrt gewähren","Vorfahrtstraße","Überholverbot"]'::jsonb,
 '["Stop!","Yield","Priority road","No overtaking"]'::jsonb,
 'Stopp — Halt!','Stop!',
 NULL, NULL,
 30)

ON CONFLICT (license_class, order_index) DO NOTHING;
