-- ============================================================
-- DeutschPilot – Driving Theory (Klasse A / motorcycle), 20 questions
-- Same rules as the Klasse B seed files: original prep questions
-- on well-established German traffic-law topics, not verbatim
-- official Fragenkatalog content.
-- ============================================================

INSERT INTO public.driving_theory_questions
  (license_class, category, question_de, question_en, options_de, options_en, correct_answer_de, correct_answer_en, explanation_de, explanation_en, order_index)
VALUES

-- Schutzausrüstung
('A','Schutzausrüstung',
 'Das Tragen eines Helms für Motorradfahrer und Beifahrer ist in Deutschland...',
 'Wearing a helmet for motorcycle riders and passengers in Germany is...',
 '["gesetzlich vorgeschrieben","nur bei über 50 km/h Pflicht","freiwillig","nur außerorts Pflicht"]'::jsonb,
 '["a legal requirement","only required above 50 km/h","voluntary","only required outside built-up areas"]'::jsonb,
 'gesetzlich vorgeschrieben','a legal requirement',
 NULL, NULL, 1),

('A','Schutzausrüstung',
 'Geeignete Schutzkleidung (Jacke, Hose, Handschuhe, feste Schuhe) beim Motorradfahren...',
 'Appropriate protective gear (jacket, trousers, gloves, sturdy shoes) when riding...',
 '["wird dringend empfohlen, auch wenn nicht jedes Teil gesetzlich einzeln vorgeschrieben ist","ist komplett gesetzlich vorgeschrieben inklusive Farbe","ist unnötig bei kurzen Strecken","ist nur im Winter sinnvoll"]'::jsonb,
 '["is strongly recommended, even though not every single item is individually mandated by law","is fully legally required including color","is unnecessary for short distances","is only useful in winter"]'::jsonb,
 'wird dringend empfohlen, auch wenn nicht jedes Teil gesetzlich einzeln vorgeschrieben ist',
 'is strongly recommended, even though not every single item is individually mandated by law',
 NULL, NULL, 2),

('A','Schutzausrüstung',
 'Helle oder reflektierende Kleidung auf dem Motorrad...',
 'Bright or reflective clothing on a motorcycle...',
 '["erhöht die Sichtbarkeit für andere Verkehrsteilnehmer","hat keinen sicherheitsrelevanten Effekt","ist gesetzlich verboten","ist nur bei Regen sinnvoll"]'::jsonb,
 '["increases visibility to other road users","has no safety-relevant effect","is legally prohibited","is only useful in the rain"]'::jsonb,
 'erhöht die Sichtbarkeit für andere Verkehrsteilnehmer',
 'increases visibility to other road users',
 NULL, NULL, 3),

-- Fahrtechnik & Gleichgewicht
('A','Fahrtechnik & Gleichgewicht',
 'Beim Durchfahren einer Kurve auf dem Motorrad ist wichtig...',
 'When riding through a curve on a motorcycle, it is important to...',
 '["Blick in die Kurve richten und gleichmäßig Gas geben","abrupt bremsen mitten in der Kurve","die Augen auf den Vorderreifen richten","möglichst aufrecht bleiben, egal wie eng die Kurve ist"]'::jsonb,
 '["look through the curve and apply throttle smoothly","brake abruptly mid-curve","focus your eyes on the front tire","stay as upright as possible regardless of curve tightness"]'::jsonb,
 'Blick in die Kurve richten und gleichmäßig Gas geben',
 'look through the curve and apply throttle smoothly',
 NULL, NULL, 4),

('A','Fahrtechnik & Gleichgewicht',
 'Eine Vollbremsung auf dem Motorrad erfordert in der Regel...',
 'Emergency braking on a motorcycle generally requires...',
 '["dosiertes Bremsen mit Vorder- und Hinterradbremse gleichzeitig","nur die Hinterradbremse zu nutzen","nur die Vorderradbremse ruckartig zu ziehen","das Kuppeln zu vergessen"]'::jsonb,
 '["controlled braking using both front and rear brakes together","using only the rear brake","yanking only the front brake abruptly","forgetting to use the clutch"]'::jsonb,
 'dosiertes Bremsen mit Vorder- und Hinterradbremse gleichzeitig',
 'controlled braking using both front and rear brakes together',
 NULL, NULL, 5),

('A','Fahrtechnik & Gleichgewicht',
 'Bei nasser Fahrbahn sollte ein Motorradfahrer...',
 'On a wet road surface, a motorcyclist should...',
 '["Geschwindigkeit reduzieren und ruckartige Lenk-/Bremsbewegungen vermeiden","normal weiterfahren wie bei Trockenheit","schneller fahren, um Pfützen zu überspringen","nur die Vorderradbremse benutzen"]'::jsonb,
 '["reduce speed and avoid abrupt steering/braking inputs","continue as if the road were dry","go faster to skip over puddles","only use the front brake"]'::jsonb,
 'Geschwindigkeit reduzieren und ruckartige Lenk-/Bremsbewegungen vermeiden',
 'reduce speed and avoid abrupt steering/braking inputs',
 NULL, NULL, 6),

('A','Fahrtechnik & Gleichgewicht',
 'Fahrbahnmarkierungen, Kanaldeckel und Straßenbahnschienen sind für Motorradfahrer bei Nässe besonders...',
 'Road markings, manhole covers, and tram tracks are especially tricky for motorcyclists in wet conditions because...',
 '["rutschig, daher besser meiden oder mit Vorsicht überfahren","völlig unbedenklich","nur bei Trockenheit relevant","nur für Autos relevant"]'::jsonb,
 '["they can be slippery, so it''s better to avoid or cross them carefully","completely harmless","only relevant when dry","only relevant for cars"]'::jsonb,
 'rutschig, daher besser meiden oder mit Vorsicht überfahren',
 'they can be slippery, so it''s better to avoid or cross them carefully',
 NULL, NULL, 7),

-- Sichtbarkeit & Positionierung
('A','Sichtbarkeit & Positionierung',
 'Motorradfahrer befinden sich im "toten Winkel" von Autos...',
 'Motorcyclists are in a car''s "blind spot"...',
 '["häufiger als größere Fahrzeuge, wegen der kleineren Silhouette","nie, weil sie so laut sind","nur bei Nacht","nur wenn sie zu schnell fahren"]'::jsonb,
 '["more often than larger vehicles, due to their smaller silhouette","never, because they are loud","only at night","only if riding too fast"]'::jsonb,
 'häufiger als größere Fahrzeuge, wegen der kleineren Silhouette',
 'more often than larger vehicles, due to their smaller silhouette',
 'Deshalb sollten Motorradfahrer aktiv defensiv fahren und immer mit Übersehen-Werden rechnen.',
 'This is why motorcyclists should ride defensively and always assume they might not be seen.',
 8),

('A','Sichtbarkeit & Positionierung',
 'Das Fahren mit eingeschaltetem Abblendlicht am Tag ist für Motorräder in Deutschland...',
 'Riding with the low-beam headlight on during the day is, for motorcycles in Germany...',
 '["ohnehin Pflicht bzw. das Licht ist fest verbaut/immer an","verboten","nur bei Regen erlaubt","nur nachts sinnvoll"]'::jsonb,
 '["already required, or the light is permanently wired on","prohibited","only allowed in rain","only useful at night"]'::jsonb,
 'ohnehin Pflicht bzw. das Licht ist fest verbaut/immer an',
 'already required, or the light is permanently wired on',
 NULL, NULL, 9),

('A','Sichtbarkeit & Positionierung',
 'Die eigene Position auf der Fahrbahn (linker, mittlerer oder rechter Bereich der Spur) sollte ein Motorradfahrer wählen, um...',
 'A motorcyclist should choose their lane position (left, center, or right of the lane) in order to...',
 '["möglichst gut gesehen zu werden und Ausweichraum zu haben","immer in der Mitte zu bleiben, egal was passiert","möglichst nah am Bordstein zu fahren","der Fahrbahnmarkierung exakt zu folgen"]'::jsonb,
 '["be seen as well as possible and have room to maneuver","always stay centered no matter what","stay as close to the curb as possible","follow the lane marking exactly"]'::jsonb,
 'möglichst gut gesehen zu werden und Ausweichraum zu haben',
 'be seen as well as possible and have room to maneuver',
 NULL, NULL, 10),

-- Gemeinsame Regeln & Sonstiges
('A','Gemeinsame Regeln & Sonstiges',
 'Die Promillegrenzen (0,5‰ allgemein, 0,0‰ für Fahranfänger/unter 21) gelten für Motorradfahrer...',
 'The blood alcohol limits (0.5‰ general, 0.0‰ for new drivers/under 21) apply to motorcyclists...',
 '["genauso wie für Autofahrer","gar nicht","nur bei Nässe","nur außerorts"]'::jsonb,
 '["just as they do for car drivers","not at all","only in wet conditions","only outside built-up areas"]'::jsonb,
 'genauso wie für Autofahrer','just as they do for car drivers',
 NULL, NULL, 11),

('A','Gemeinsame Regeln & Sonstiges',
 'Beim Fahren in einer Motorradgruppe sollte der Abstand zum Vordermann...',
 'When riding in a group of motorcyclists, the distance to the rider ahead should...',
 '["ausreichend groß sein, um bei plötzlichem Bremsen sicher reagieren zu können","möglichst klein sein, um die Gruppe zusammenzuhalten","keine Rolle spielen","nur bei Regen vergrößert werden"]'::jsonb,
 '["be large enough to react safely to sudden braking","be as small as possible to keep the group together","not matter at all","only be increased in the rain"]'::jsonb,
 'ausreichend groß sein, um bei plötzlichem Bremsen sicher reagieren zu können',
 'be large enough to react safely to sudden braking',
 NULL, NULL, 12),

('A','Gemeinsame Regeln & Sonstiges',
 'Ein "Reifendruck-Check" vor längeren Motorradfahrten ist wichtig, weil...',
 'A tire pressure check before longer motorcycle rides is important because...',
 '["falscher Reifendruck Fahrstabilität und Bremsverhalten beeinträchtigt","Reifendruck bei Motorrädern keine Rolle spielt","es nur um den Kraftstoffverbrauch geht","es gesetzlich egal ist"]'::jsonb,
 '["incorrect tire pressure impairs stability and braking behavior","tire pressure doesn''t matter on motorcycles","it is only about fuel consumption","it is legally irrelevant"]'::jsonb,
 'falscher Reifendruck Fahrstabilität und Bremsverhalten beeinträchtigt',
 'incorrect tire pressure impairs stability and braking behavior',
 NULL, NULL, 13),

('A','Gemeinsame Regeln & Sonstiges',
 'Rechtsüberholen und das Vorbeifahren an einer Kolonne stehender/langsamer Autos mit dem Motorrad...',
 'Overtaking on the right or filtering past a column of stopped/slow cars on a motorcycle...',
 '["ist grundsätzlich riskant und in vielen Situationen unzulässig, besondere Vorsicht ist geboten","ist immer uneingeschränkt erlaubt","ist ausdrücklich empfohlen, um Zeit zu sparen","betrifft nur Autos, nicht Motorräder"]'::jsonb,
 '["is generally risky and in many situations not permitted; extra caution is required","is always unrestricted and allowed","is explicitly recommended to save time","only applies to cars, not motorcycles"]'::jsonb,
 'ist grundsätzlich riskant und in vielen Situationen unzulässig, besondere Vorsicht ist geboten',
 'is generally risky and in many situations not permitted; extra caution is required',
 NULL, NULL, 14),

('A','Gemeinsame Regeln & Sonstiges',
 'Warum sind Motorräder bei Seitenwind (z. B. beim Überholtwerden von LKW) besonders gefährdet?',
 'Why are motorcycles especially vulnerable to crosswinds (e.g. when being overtaken by a truck)?',
 '["weil sie leichter sind und leichter aus der Spur gedrückt werden können","weil sie schwerer sind als Autos","Seitenwind betrifft Motorräder gar nicht","nur bei sehr hoher Geschwindigkeit relevant"]'::jsonb,
 '["because they are lighter and can more easily be pushed off line","because they are heavier than cars","crosswind doesn''t affect motorcycles at all","only relevant at very high speed"]'::jsonb,
 'weil sie leichter sind und leichter aus der Spur gedrückt werden können',
 'because they are lighter and can more easily be pushed off line',
 NULL, NULL, 15),

('A','Gemeinsame Regeln & Sonstiges',
 'Die Zuladung (Gepäck, Sozius) beeinflusst beim Motorrad...',
 'Load (luggage, passenger) affects a motorcycle''s...',
 '["Fahrverhalten, Bremsweg und Schwerpunkt","gar nichts, solange das Gewichtslimit eingehalten wird","nur die Optik","nur den Kraftstoffverbrauch"]'::jsonb,
 '["handling, braking distance, and center of gravity","nothing at all, as long as the weight limit is respected","only appearance","only fuel consumption"]'::jsonb,
 'Fahrverhalten, Bremsweg und Schwerpunkt',
 'handling, braking distance, and center of gravity',
 NULL, NULL, 16),

('A','Gemeinsame Regeln & Sonstiges',
 'Regelmäßige Wartung (Kette, Bremsen, Reifenprofil) ist beim Motorrad...',
 'Regular maintenance (chain, brakes, tire tread) on a motorcycle is...',
 '["besonders sicherheitsrelevant, da Defekte oft direkt zum Sturz führen können","weniger wichtig als beim Auto","nur bei alten Motorrädern nötig","gesetzlich nicht vorgeschrieben und daher irrelevant"]'::jsonb,
 '["especially safety-critical, since defects can often directly cause a crash","less important than for a car","only necessary for old motorcycles","legally not required and therefore irrelevant"]'::jsonb,
 'besonders sicherheitsrelevant, da Defekte oft direkt zum Sturz führen können',
 'especially safety-critical, since defects can often directly cause a crash',
 NULL, NULL, 17),

('A','Gemeinsame Regeln & Sonstiges',
 'Kalte Reifen (z. B. direkt nach Fahrtbeginn) bieten im Vergleich zu warmgefahrenen Reifen...',
 'Cold tires (e.g. right after starting a ride) offer, compared to warmed-up tires...',
 '["weniger Grip, daher anfangs vorsichtiger fahren","mehr Grip","exakt denselben Grip","nur bei Nässe weniger Grip"]'::jsonb,
 '["less grip, so ride more cautiously at first","more grip","exactly the same grip","less grip only in wet conditions"]'::jsonb,
 'weniger Grip, daher anfangs vorsichtiger fahren',
 'less grip, so ride more cautiously at first',
 NULL, NULL, 18),

('A','Gemeinsame Regeln & Sonstiges',
 'Die zulässige Höchstgeschwindigkeit innerorts (i. d. R. 50 km/h) und außerorts (i. d. R. 100 km/h) gilt...',
 'The general speed limits within built-up areas (usually 50 km/h) and outside them (usually 100 km/h) apply...',
 '["für Motorräder genauso wie für PKW, sofern nicht anders beschildert","nicht für Motorräder","nur für Motorräder über 500 ccm","nur außerorts für Motorräder"]'::jsonb,
 '["to motorcycles just as they do to cars, unless otherwise signed","not to motorcycles","only to motorcycles over 500cc","only outside built-up areas for motorcycles"]'::jsonb,
 'für Motorräder genauso wie für PKW, sofern nicht anders beschildert',
 'to motorcycles just as they do to cars, unless otherwise signed',
 NULL, NULL, 19),

('A','Gemeinsame Regeln & Sonstiges',
 'Beim Rangieren oder sehr langsamen Fahren (z. B. im Stau) neigen Motorräder dazu...',
 'When maneuvering or riding very slowly (e.g. in traffic jams), motorcycles tend to...',
 '["instabiler zu werden, da der Kreiseleffekt der Räder bei geringem Tempo abnimmt","stabiler zu werden als bei hoher Geschwindigkeit","sich gar nicht anders zu verhalten","nur bei Regen instabil zu werden"]'::jsonb,
 '["become less stable, since the gyroscopic effect of the wheels decreases at low speed","become more stable than at high speed","behave exactly the same regardless of speed","only become unstable in the rain"]'::jsonb,
 'instabiler zu werden, da der Kreiseleffekt der Räder bei geringem Tempo abnimmt',
 'become less stable, since the gyroscopic effect of the wheels decreases at low speed',
 NULL, NULL, 20)

ON CONFLICT (license_class, order_index) DO NOTHING;
