-- ============================================================
-- DeutschPilot – Driving Theory (Klasse B) batch 3, 20 more questions
-- Same rules as batches 1-2: original prep questions on well-
-- established traffic-law topics, not verbatim official content.
-- ============================================================

INSERT INTO public.driving_theory_questions
  (license_class, category, question_de, question_en, options_de, options_en, correct_answer_de, correct_answer_en, explanation_de, explanation_en, order_index)
VALUES

-- Fahrzeugpapiere & Versicherung
('B','Fahrzeugpapiere & Versicherung',
 'Welches Dokument musst du beim Fahren immer mitführen?',
 'Which document must you always carry while driving?',
 '["den Führerschein","die Kfz-Steuerbescheinigung","den Kaufvertrag des Autos","gar keines"]'::jsonb,
 '["your driving license","the vehicle tax certificate","the car purchase contract","none"]'::jsonb,
 'den Führerschein','your driving license',
 'Die Zulassungsbescheinigung Teil I (Fahrzeugschein) muss ebenfalls mitgeführt werden.',
 'The vehicle registration certificate part I must also be carried.',
 55),

('B','Fahrzeugpapiere & Versicherung',
 'Die Kfz-Haftpflichtversicherung ist in Deutschland...',
 'Third-party liability insurance for vehicles in Germany is...',
 '["gesetzlich vorgeschrieben für jedes zugelassene Fahrzeug","optional","nur für Neuwagen Pflicht","nur für gewerbliche Fahrzeuge Pflicht"]'::jsonb,
 '["legally required for every registered vehicle","optional","only mandatory for new cars","only mandatory for commercial vehicles"]'::jsonb,
 'gesetzlich vorgeschrieben für jedes zugelassene Fahrzeug',
 'legally required for every registered vehicle',
 NULL, NULL, 56),

('B','Fahrzeugpapiere & Versicherung',
 'Der TÜV / die Hauptuntersuchung (HU) prüft...',
 'The TÜV / main inspection (HU) checks...',
 '["die Verkehrssicherheit und Umweltverträglichkeit des Fahrzeugs","nur den Kilometerstand","nur die Farbe des Autos","nur das Radio"]'::jsonb,
 '["the vehicle''s road safety and environmental compliance","only the odometer reading","only the car''s color","only the radio"]'::jsonb,
 'die Verkehrssicherheit und Umweltverträglichkeit des Fahrzeugs',
 'the vehicle''s road safety and environmental compliance',
 NULL, NULL, 57),

('B','Fahrzeugpapiere & Versicherung',
 'Fährst du ohne gültige Hauptuntersuchung (abgelaufene Plakette), riskierst du...',
 'Driving with an expired main inspection sticker risks...',
 '["ein Bußgeld und ggf. einen Punkt in Flensburg","gar nichts","nur eine mündliche Verwarnung","den Verlust des Führerscheins beim ersten Mal"]'::jsonb,
 '["a fine and possibly a point on your license","nothing at all","only a verbal warning","losing your license on the first offense"]'::jsonb,
 'ein Bußgeld und ggf. einen Punkt in Flensburg',
 'a fine and possibly a point on your license',
 NULL, NULL, 58),

-- Unfall & Erste Hilfe
('B','Unfall & Erste Hilfe',
 'Bei einem Verkehrsunfall mit Verletzten musst du...',
 'At a traffic accident with injured people, you must...',
 '["die Unfallstelle absichern, Erste Hilfe leisten und den Notruf wählen","einfach weiterfahren","nur die Polizei rufen, sonst nichts tun","warten, bis jemand anderes hilft"]'::jsonb,
 '["secure the accident scene, provide first aid, and call emergency services","just drive on","only call the police and do nothing else","wait until someone else helps"]'::jsonb,
 'die Unfallstelle absichern, Erste Hilfe leisten und den Notruf wählen',
 'secure the accident scene, provide first aid, and call emergency services',
 NULL, NULL, 59),

('B','Unfall & Erste Hilfe',
 'Die europaweite Notrufnummer für Notfälle ist...',
 'The Europe-wide emergency number is...',
 '["112","911","100","000"]'::jsonb,
 '["112","911","100","000"]'::jsonb,
 '112','112',
 NULL, NULL, 60),

('B','Unfall & Erste Hilfe',
 'Ein Warndreieck solltest du bei einer Panne oder einem Unfall auf der Autobahn in welcher Entfernung aufstellen?',
 'At what distance should you place a warning triangle in case of a breakdown or accident on the Autobahn?',
 '["etwa 100 Meter vor der Gefahrenstelle","direkt neben dem Auto","es ist nicht nötig","nur 5 Meter davor"]'::jsonb,
 '["about 100 meters before the hazard","right next to the car","it is not necessary","only 5 meters before it"]'::jsonb,
 'etwa 100 Meter vor der Gefahrenstelle',
 'about 100 meters before the hazard',
 NULL, NULL, 61),

('B','Unfall & Erste Hilfe',
 'Unterlassene Hilfeleistung bei einem Unfall ist in Deutschland...',
 'Failing to render assistance at an accident in Germany is...',
 '["eine Straftat","nur unhöflich, aber nicht strafbar","nur bei eigenem Verschulden strafbar","erlaubt, wenn man in Eile ist"]'::jsonb,
 '["a criminal offense","only impolite, not punishable","only punishable if you caused the accident","allowed if you are in a hurry"]'::jsonb,
 'eine Straftat','a criminal offense',
 NULL, NULL, 62),

('B','Unfall & Erste Hilfe',
 'Nach einem kleinen Blechschaden ohne Verletzte solltest du...',
 'After a minor fender-bender with no injuries, you should...',
 '["die Kontaktdaten austauschen und ggf. die Polizei informieren","einfach wegfahren","nichts unternehmen","nur den Schaden fotografieren und nichts weiter sagen"]'::jsonb,
 '["exchange contact details and inform the police if needed","just drive away","do nothing","only photograph the damage and say nothing else"]'::jsonb,
 'die Kontaktdaten austauschen und ggf. die Polizei informieren',
 'exchange contact details and inform the police if needed',
 'Unerlaubtes Entfernen vom Unfallort (Fahrerflucht) ist strafbar, auch bei kleinen Schäden.',
 'Leaving the scene without authorization (hit and run) is a criminal offense, even for minor damage.',
 63),

-- Ladung & Anhänger
('B','Ladung & Anhänger',
 'Die Ladung im Fahrzeug muss...',
 'The load in the vehicle must be...',
 '["so gesichert sein, dass sie auch bei Vollbremsung nicht verrutscht","gar nicht gesichert werden, wenn sie leicht ist","nur bei langen Fahrten gesichert werden","nur im Kofferraum gesichert werden"]'::jsonb,
 '["secured so that it doesn''t shift even during emergency braking","not secured at all if it is light","only secured on long trips","only secured if in the trunk"]'::jsonb,
 'so gesichert sein, dass sie auch bei Vollbremsung nicht verrutscht',
 'secured so that it doesn''t shift even during emergency braking',
 NULL, NULL, 64),

('B','Ladung & Anhänger',
 'Überladung eines Fahrzeugs...',
 'Overloading a vehicle...',
 '["beeinträchtigt Bremsverhalten und Fahrstabilität und ist ordnungswidrig","ist ohne Folgen für die Fahreigenschaften","ist immer erlaubt, wenn gut verteilt","betrifft nur LKW"]'::jsonb,
 '["impairs braking and handling and is an administrative offense","has no effect on driving characteristics","is always allowed if well distributed","only applies to trucks"]'::jsonb,
 'beeinträchtigt Bremsverhalten und Fahrstabilität und ist ordnungswidrig',
 'impairs braking and handling and is an administrative offense',
 NULL, NULL, 65),

('B','Ladung & Anhänger',
 'Mit einem Führerschein der Klasse B darfst du in der Regel einen Anhänger fahren bis zu einer zulässigen Gesamtmasse (Kombination) von...',
 'With a Class B license, you may generally tow a trailer up to a combined permissible total weight of...',
 '["3.500 kg","1.000 kg","7.500 kg","unbegrenzt"]'::jsonb,
 '["3,500 kg","1,000 kg","7,500 kg","unlimited"]'::jsonb,
 '3.500 kg','3,500 kg',
 'Für schwerere Kombinationen ist die Erweiterung "BE" oder eine höhere Klasse nötig.',
 'For heavier combinations, the "BE" extension or a higher license class is required.',
 66),

('B','Ladung & Anhänger',
 'Beim Fahren mit Anhänger verlängert sich in der Regel...',
 'When driving with a trailer, what generally increases is...',
 '["der Bremsweg","die Höchstgeschwindigkeit","die Reifenlebensdauer","die Sichtweite"]'::jsonb,
 '["the braking distance","the maximum speed","tire lifespan","visibility range"]'::jsonb,
 'der Bremsweg','the braking distance',
 NULL, NULL, 67),

-- Fahrtüchtigkeit & Müdigkeit
('B','Fahrtüchtigkeit & Müdigkeit',
 'Müdigkeit am Steuer beeinträchtigt...',
 'Fatigue while driving impairs...',
 '["Reaktionsvermögen und Konzentration erheblich","nichts, solange man wach bleibt","nur die Laune","nur bei langen Autobahnfahrten"]'::jsonb,
 '["reaction ability and concentration significantly","nothing, as long as you stay awake","only your mood","only on long motorway drives"]'::jsonb,
 'Reaktionsvermögen und Konzentration erheblich',
 'reaction ability and concentration significantly',
 NULL, NULL, 68),

('B','Fahrtüchtigkeit & Müdigkeit',
 'Bestimmte Medikamente (z. B. manche Erkältungs- oder Schlafmittel) können...',
 'Certain medications (e.g. some cold or sleep remedies) can...',
 '["die Fahrtüchtigkeit beeinträchtigen, auch wenn sie legal und verschreibungsfrei sind","niemals die Fahrtüchtigkeit beeinflussen","nur bei Überdosierung wirken","nur bei älteren Menschen wirken"]'::jsonb,
 '["impair fitness to drive, even if they are legal and over-the-counter","never affect fitness to drive","only have an effect if overdosed","only affect older people"]'::jsonb,
 'die Fahrtüchtigkeit beeinträchtigen, auch wenn sie legal und verschreibungsfrei sind',
 'impair fitness to drive, even if they are legal and over-the-counter',
 NULL, NULL, 69),

('B','Fahrtüchtigkeit & Müdigkeit',
 'Bei aufkommender Müdigkeit während der Fahrt solltest du...',
 'If you start feeling drowsy while driving, you should...',
 '["so früh wie möglich eine Pause einlegen","das Fenster öffnen und weiterfahren","die Musik lauter stellen und weiterfahren","erst bei starker Müdigkeit reagieren"]'::jsonb,
 '["take a break as early as possible","open the window and keep driving","turn up the music and keep driving","only react once fatigue is severe"]'::jsonb,
 'so früh wie möglich eine Pause einlegen',
 'take a break as early as possible',
 NULL, NULL, 70),

-- Umwelt & Fahrverhalten
('B','Umwelt & Fahrverhalten',
 'Vorausschauendes, gleichmäßiges Fahren (ohne starkes Beschleunigen/Bremsen)...',
 'Anticipatory, smooth driving (without heavy acceleration/braking)...',
 '["spart Kraftstoff und reduziert Verschleiß","hat keinen Effekt auf den Verbrauch","erhöht immer den Verbrauch","ist nur auf der Autobahn relevant"]'::jsonb,
 '["saves fuel and reduces wear","has no effect on fuel consumption","always increases fuel consumption","is only relevant on the Autobahn"]'::jsonb,
 'spart Kraftstoff und reduziert Verschleiß',
 'saves fuel and reduces wear',
 NULL, NULL, 71),

('B','Umwelt & Fahrverhalten',
 'Frühzeitiges Hochschalten der Gänge (niedrige Drehzahl)...',
 'Shifting up gears early (low RPM)...',
 '["senkt in der Regel den Kraftstoffverbrauch","erhöht immer den Verbrauch","hat keinen Einfluss auf den Verbrauch","ist nur bei Automatikgetrieben relevant"]'::jsonb,
 '["generally lowers fuel consumption","always increases consumption","has no effect on consumption","is only relevant for automatic transmissions"]'::jsonb,
 'senkt in der Regel den Kraftstoffverbrauch',
 'generally lowers fuel consumption',
 NULL, NULL, 72),

('B','Umwelt & Fahrverhalten',
 'Ein regelmäßig gewarteter Reifendruck, der dem Sollwert entspricht...',
 'Tire pressure that is regularly maintained at the recommended level...',
 '["verbessert Sicherheit und senkt den Kraftstoffverbrauch","hat keinen Einfluss auf Sicherheit oder Verbrauch","erhöht nur den Verschleiß","ist nur im Sommer wichtig"]'::jsonb,
 '["improves safety and lowers fuel consumption","has no effect on safety or consumption","only increases wear","is only important in summer"]'::jsonb,
 'verbessert Sicherheit und senkt den Kraftstoffverbrauch',
 'improves safety and lowers fuel consumption',
 NULL, NULL, 73),

('B','Umwelt & Fahrverhalten',
 'Warum sollte man im Stand an einer Bahnschranke oder im Stau den Motor abstellen, wenn absehbar länger gewartet werden muss?',
 'Why should you turn off the engine while waiting at a closed railway barrier or in a jam if the wait will clearly be long?',
 '["um Kraftstoff zu sparen und unnötige Emissionen zu vermeiden","weil es gesetzlich in jedem Fall Pflicht ist, sofort abzuschalten","es gibt keinen Grund dafür","nur um die Batterie zu schonen"]'::jsonb,
 '["to save fuel and avoid unnecessary emissions","because switching off immediately is legally required in every case","there is no reason to do so","only to protect the battery"]'::jsonb,
 'um Kraftstoff zu sparen und unnötige Emissionen zu vermeiden',
 'to save fuel and avoid unnecessary emissions',
 NULL, NULL, 74)

ON CONFLICT (license_class, order_index) DO NOTHING;
