-- ============================================================
-- DeutschPilot – Driving Theory (Klasse B) batch 4, 24 more questions
-- Same rules as batches 1-3: original prep questions on well-
-- established German traffic-law topics, not verbatim official content.
-- ============================================================

INSERT INTO public.driving_theory_questions
  (license_class, category, question_de, question_en, options_de, options_en, correct_answer_de, correct_answer_en, explanation_de, explanation_en, order_index)
VALUES

-- Punkte & Bußgelder
('B','Punkte & Bußgelder',
 'Das Fahreignungsregister (früher "Verkehrszentralregister") in Flensburg erfasst...',
 'The driver fitness register (Flensburg) records...',
 '["Punkte für schwerere Verkehrsverstöße","nur Falschparker","nur Unfälle mit Personenschaden","gar keine Verstöße mehr seit 2014"]'::jsonb,
 '["points for more serious traffic offenses","only illegal parking","only accidents with injuries","no offenses at all since 2014"]'::jsonb,
 'Punkte für schwerere Verkehrsverstöße',
 'points for more serious traffic offenses',
 NULL, NULL, 75),

('B','Punkte & Bußgelder',
 'Ab wie vielen Punkten in Flensburg wird der Führerschein in der Regel entzogen?',
 'From how many points is the license generally revoked?',
 '["8 Punkten","3 Punkten","20 Punkten","es gibt kein Punktesystem mehr"]'::jsonb,
 '["8 points","3 points","20 points","there is no longer a points system"]'::jsonb,
 '8 Punkten','8 points',
 'Bei 4-5 Punkten gibt es eine Ermahnung, bei 6-7 eine Verwarnung, ab 8 den Entzug.',
 'At 4-5 points there''s a reminder, at 6-7 a warning, from 8 the license is revoked.',
 76),

('B','Punkte & Bußgelder',
 'Ein Bußgeldbescheid nach einem Verkehrsverstoß kann in der Regel...',
 'A fine notice after a traffic offense generally can...',
 '["innerhalb einer Frist angefochten werden (Einspruch)","niemals angefochten werden","nur mündlich widersprochen werden","nur von einem Anwalt bezahlt werden"]'::jsonb,
 '["be contested within a deadline (formal objection)","never be contested","only be verbally disputed","only be paid by a lawyer"]'::jsonb,
 'innerhalb einer Frist angefochten werden (Einspruch)',
 'be contested within a deadline (formal objection)',
 NULL, NULL, 77),

('B','Punkte & Bußgelder',
 'Wiederholte, geringfügige Geschwindigkeitsüberschreitungen...',
 'Repeated, minor speeding violations...',
 '["können sich zu höheren Bußgeldern und Punkten summieren","werden nach dem ersten Mal ignoriert","zählen nie zusammen","betreffen nur Berufskraftfahrer"]'::jsonb,
 '["can add up to higher fines and points over time","are ignored after the first offense","never accumulate","only apply to professional drivers"]'::jsonb,
 'können sich zu höheren Bußgeldern und Punkten summieren',
 'can add up to higher fines and points over time',
 NULL, NULL, 78),

-- Wetter & Sicht
('B','Wetter & Sicht',
 'Bei dichtem Nebel mit Sicht unter 50 Metern gilt in Deutschland...',
 'In dense fog with visibility under 50 meters, the rule in Germany is...',
 '["eine Höchstgeschwindigkeit von 50 km/h","keine Geschwindigkeitsbegrenzung","ein generelles Fahrverbot","nur Fernlicht ist erlaubt"]'::jsonb,
 '["a maximum speed of 50 km/h","no speed limit at all","a general driving ban","only high beams are allowed"]'::jsonb,
 'eine Höchstgeschwindigkeit von 50 km/h',
 'a maximum speed of 50 km/h',
 NULL, NULL, 79),

('B','Wetter & Sicht',
 'Nebelschlussleuchten dürfen genutzt werden...',
 'Rear fog lights may be used...',
 '["nur bei Sichtweite unter 50 Metern","immer bei Regen","immer nachts","nie, sie sind nur Dekoration"]'::jsonb,
 '["only when visibility is under 50 meters","always in the rain","always at night","never, they''re just decoration"]'::jsonb,
 'nur bei Sichtweite unter 50 Metern',
 'only when visibility is under 50 meters',
 'Bei besserer Sicht müssen sie wieder ausgeschaltet werden, da sie andere blenden können.',
 'Once visibility improves, they must be turned off again since they can blind other drivers.',
 80),

('B','Wetter & Sicht',
 'Aquaplaning (Wasserglätte) entsteht, wenn...',
 'Aquaplaning (hydroplaning) occurs when...',
 '["sich zwischen Reifen und Fahrbahn ein Wasserfilm bildet und der Grip verloren geht","die Reifen zu kalt sind","es schneit statt regnet","die Bremsen überhitzen"]'::jsonb,
 '["a film of water forms between the tire and road, causing loss of grip","the tires are too cold","it snows instead of rains","the brakes overheat"]'::jsonb,
 'sich zwischen Reifen und Fahrbahn ein Wasserfilm bildet und der Grip verloren geht',
 'a film of water forms between the tire and road, causing loss of grip',
 NULL, NULL, 81),

('B','Wetter & Sicht',
 'Bei Aquaplaning sollte man...',
 'In case of aquaplaning, you should...',
 '["Gas wegnehmen, Lenkrad geradeaus halten und nicht abrupt bremsen","sofort eine Vollbremsung machen","Gas geben, um durchzufahren","scharf gegenlenken"]'::jsonb,
 '["ease off the gas, hold the steering wheel straight, and avoid abrupt braking","brake as hard as possible immediately","accelerate to power through it","steer sharply in the opposite direction"]'::jsonb,
 'Gas wegnehmen, Lenkrad geradeaus halten und nicht abrupt bremsen',
 'ease off the gas, hold the steering wheel straight, and avoid abrupt braking',
 NULL, NULL, 82),

('B','Wetter & Sicht',
 'Blendung durch tiefstehende Sonne (z. B. morgens/abends)...',
 'Glare from low sun (e.g. in the morning/evening)...',
 '["kann die Sicht erheblich einschränken — Sonnenblende nutzen und Tempo anpassen","hat keine sicherheitsrelevante Wirkung","betrifft nur Motorradfahrer","tritt nur im Winter auf"]'::jsonb,
 '["can significantly impair vision — use the sun visor and adjust speed","has no safety-relevant effect","only affects motorcyclists","only happens in winter"]'::jsonb,
 'kann die Sicht erheblich einschränken — Sonnenblende nutzen und Tempo anpassen',
 'can significantly impair vision — use the sun visor and adjust speed',
 NULL, NULL, 83),

-- Kinder im Verkehr
('B','Kinder im Verkehr',
 'In der Nähe von Schulen und Spielstraßen solltest du...',
 'Near schools and play streets, you should...',
 '["besonders langsam fahren und mit unvorhersehbarem Verhalten von Kindern rechnen","normal weiterfahren wie überall","nur morgens vorsichtig sein","hupen, um Kinder zu warnen"]'::jsonb,
 '["drive especially slowly and expect unpredictable behavior from children","drive normally as anywhere else","only be cautious in the morning","honk to warn children"]'::jsonb,
 'besonders langsam fahren und mit unvorhersehbarem Verhalten von Kindern rechnen',
 'drive especially slowly and expect unpredictable behavior from children',
 NULL, NULL, 84),

('B','Kinder im Verkehr',
 'Ein Ball, der plötzlich auf die Straße rollt, ist ein Warnzeichen dafür, dass...',
 'A ball suddenly rolling onto the road is a warning sign that...',
 '["ein Kind ihm folgen könnte — sofort verlangsamen","nichts Besonderes passiert ist","man beschleunigen sollte, um vorbeizukommen","es sich um ein Verkehrsschild handelt"]'::jsonb,
 '["a child might follow it — slow down immediately","nothing in particular has happened","you should speed up to get past","it''s some kind of traffic sign"]'::jsonb,
 'ein Kind ihm folgen könnte — sofort verlangsamen',
 'a child might follow it — slow down immediately',
 NULL, NULL, 85),

('B','Kinder im Verkehr',
 'In einer "Spielstraße" (Zeichen: spielende Kinder) gilt...',
 'In a "play street" (sign: children playing)...',
 '["Schrittgeschwindigkeit, Fußgänger dürfen die gesamte Straße nutzen","normale Höchstgeschwindigkeit von 50 km/h","ein generelles Fahrverbot für Autos","nur Vorsicht bei Kindern unter 6 Jahren"]'::jsonb,
 '["walking pace, and pedestrians may use the entire street","the normal 50 km/h speed limit","a general ban on cars","caution is only required for children under 6"]'::jsonb,
 'Schrittgeschwindigkeit, Fußgänger dürfen die gesamte Straße nutzen',
 'walking pace, and pedestrians may use the entire street',
 NULL, NULL, 86),

-- Nachtfahrt
('B','Nachtfahrt',
 'Beim Fahren in der Dämmerung oder Nacht solltest du...',
 'When driving at dusk or at night, you should...',
 '["das Tempo an die reduzierte Sicht anpassen, auch wenn die Straße bekannt ist","genauso schnell fahren wie am Tag","nur das Standlicht benutzen","die Scheinwerfer möglichst spät einschalten"]'::jsonb,
 '["adjust your speed to the reduced visibility, even on familiar roads","drive just as fast as during the day","only use parking lights","turn on headlights as late as possible"]'::jsonb,
 'das Tempo an die reduzierte Sicht anpassen, auch wenn die Straße bekannt ist',
 'adjust your speed to the reduced visibility, even on familiar roads',
 NULL, NULL, 87),

('B','Nachtfahrt',
 'Fernlicht sollte rechtzeitig abgeblendet werden, wenn...',
 'High beams should be dimmed in good time when...',
 '["dir ein Fahrzeug entgegenkommt oder du ein Fahrzeug einholst","es zu regnen beginnt","du auf der Autobahn fährst","die Straße leer ist"]'::jsonb,
 '["an oncoming vehicle approaches or you catch up to another vehicle","it starts raining","you''re on the motorway","the road is empty"]'::jsonb,
 'dir ein Fahrzeug entgegenkommt oder du ein Fahrzeug einholst',
 'an oncoming vehicle approaches or you catch up to another vehicle',
 NULL, NULL, 88),

('B','Nachtfahrt',
 'Nachts ist das Erkennen von Fußgängern und Radfahrern ohne Reflektoren/Beleuchtung...',
 'At night, spotting pedestrians and cyclists without reflectors/lights is...',
 '["deutlich erschwert — besondere Aufmerksamkeit ist nötig","genauso einfach wie am Tag","irrelevant, da sie selbst aufpassen müssen","nur an Kreuzungen ein Problem"]'::jsonb,
 '["significantly harder — extra attention is required","just as easy as during the day","irrelevant, since they must watch out themselves","only a problem at intersections"]'::jsonb,
 'deutlich erschwert — besondere Aufmerksamkeit ist nötig',
 'significantly harder — extra attention is required',
 NULL, NULL, 89),

-- Reifen & Technik
('B','Reifen & Technik',
 'Die gesetzliche Mindestprofiltiefe für PKW-Reifen in Deutschland beträgt...',
 'The legal minimum tire tread depth for cars in Germany is...',
 '["1,6 Millimeter","3 Millimeter","0,5 Millimeter","es gibt keine gesetzliche Vorgabe"]'::jsonb,
 '["1.6 millimeters","3 millimeters","0.5 millimeters","there is no legal requirement"]'::jsonb,
 '1,6 Millimeter','1.6 millimeters',
 'Für Winterreifen wird aus Sicherheitsgründen oft mehr Profiltiefe empfohlen als gesetzlich gefordert.',
 'For winter tires, more tread depth than the legal minimum is often recommended for safety.',
 90),

('B','Reifen & Technik',
 'Funktionierende Bremslichter und Blinker sind...',
 'Functioning brake lights and turn signals are...',
 '["Teil der vorgeschriebenen Verkehrssicherheit deines Fahrzeugs","optional, solange man vorsichtig fährt","nur bei der Hauptuntersuchung relevant","nur bei Nacht wichtig"]'::jsonb,
 '["part of your vehicle''s required road safety equipment","optional as long as you drive carefully","only relevant at the main inspection","only important at night"]'::jsonb,
 'Teil der vorgeschriebenen Verkehrssicherheit deines Fahrzeugs',
 'part of your vehicle''s required road safety equipment',
 NULL, NULL, 91),

('B','Reifen & Technik',
 'Ein Warndreieck, ein Verbandskasten und eine Warnweste gehören zur...',
 'A warning triangle, first-aid kit, and warning vest are part of the...',
 '["vorgeschriebenen Fahrzeugausstattung in Deutschland","optionalen Sonderausstattung","Ausstattung, die nur im Ausland Pflicht ist","reinen Empfehlung ohne rechtliche Grundlage"]'::jsonb,
 '["mandatory vehicle equipment in Germany","optional special equipment","equipment only required abroad","a pure recommendation with no legal basis"]'::jsonb,
 'vorgeschriebenen Fahrzeugausstattung in Deutschland',
 'mandatory vehicle equipment in Germany',
 NULL, NULL, 92),

('B','Reifen & Technik',
 'Ungleicher Reifendruck zwischen den Rädern kann...',
 'Unequal tire pressure between wheels can...',
 '["das Fahrverhalten und die Bremswirkung negativ beeinflussen","keinen Unterschied machen","nur den Komfort beeinflussen, nicht die Sicherheit","nur bei Regen relevant sein"]'::jsonb,
 '["negatively affect handling and braking performance","make no difference at all","only affect comfort, not safety","only be relevant in the rain"]'::jsonb,
 'das Fahrverhalten und die Bremswirkung negativ beeinflussen',
 'negatively affect handling and braking performance',
 NULL, NULL, 93),

-- Sonstiges
('B','Sonstiges',
 'Elektrofahrzeuge sind im Vergleich zu Verbrennerfahrzeugen bei niedrigem Tempo oft...',
 'Compared to combustion-engine cars, electric vehicles at low speed are often...',
 '["deutlich leiser, weshalb Fußgänger sie später bemerken können","lauter","identisch im Geräuschpegel","gesetzlich zum ständigen Hupen verpflichtet"]'::jsonb,
 '["noticeably quieter, so pedestrians may notice them later","louder","identical in noise level","legally required to honk constantly"]'::jsonb,
 'deutlich leiser, weshalb Fußgänger sie später bemerken können',
 'noticeably quieter, so pedestrians may notice them later',
 'Viele E-Fahrzeuge haben deshalb ein akustisches Warnsystem (AVAS) bei niedrigem Tempo.',
 'Many EVs therefore have an acoustic warning system (AVAS) at low speeds.',
 94),

('B','Sonstiges',
 'Beim Auffahren auf die Autobahn über den Beschleunigungsstreifen solltest du...',
 'When merging onto the motorway via the acceleration lane, you should...',
 '["auf die Geschwindigkeit des fließenden Verkehrs beschleunigen, bevor du einfädelst","langsam bleiben und sofort einfädeln","auf dem Beschleunigungsstreifen stehen bleiben","rückwärtsfahren, falls kein Platz ist"]'::jsonb,
 '["accelerate to match the flowing traffic before merging in","stay slow and merge immediately","stop on the acceleration lane","reverse if there''s no space"]'::jsonb,
 'auf die Geschwindigkeit des fließenden Verkehrs beschleunigen, bevor du einfädelst',
 'accelerate to match the flowing traffic before merging in',
 NULL, NULL, 95),

('B','Sonstiges',
 'Beim Einfädeln nach dem Reißverschlussverfahren...',
 'When merging using the "zipper" (alternating) method...',
 '["lassen sich die Fahrzeuge beider Spuren abwechselnd einfädeln, kurz vor der Verengung","hat immer die rechte Spur Vorfahrt","hat immer die linke Spur Vorfahrt","muss die eine Spur komplett anhalten"]'::jsonb,
 '["vehicles from both lanes take turns merging, right at the point of narrowing","the right lane always has priority","the left lane always has priority","one lane must come to a complete stop"]'::jsonb,
 'lassen sich die Fahrzeuge beider Spuren abwechselnd einfädeln, kurz vor der Verengung',
 'vehicles from both lanes take turns merging, right at the point of narrowing',
 NULL, NULL, 96),

('B','Sonstiges',
 'Autonome Fahrassistenzsysteme (z. B. Abstandsregeltempomat, Spurhalteassistent)...',
 'Advanced driver-assistance systems (e.g. adaptive cruise control, lane-keep assist)...',
 '["unterstützen den Fahrer, entbinden ihn aber nicht von der Verantwortung","übernehmen die volle rechtliche Verantwortung","machen aufmerksames Fahren überflüssig","sind in Deutschland verboten"]'::jsonb,
 '["assist the driver but do not remove their responsibility","take over full legal responsibility","make attentive driving unnecessary","are illegal in Germany"]'::jsonb,
 'unterstützen den Fahrer, entbinden ihn aber nicht von der Verantwortung',
 'assist the driver but do not remove their responsibility',
 NULL, NULL, 97),

('B','Sonstiges',
 'Beim Verlassen des Fahrzeugs (Aussteigen) solltest du besonders auf...',
 'When getting out of the car, you should pay special attention to...',
 '["den rückwärtigen Verkehr achten, um Radfahrer/Autos nicht zu gefährden (\"Holländischer Griff\")","gar nichts achten müssen","nur auf Fußgänger vor dem Auto achten","nur bei Regen aufpassen"]'::jsonb,
 '["traffic approaching from behind, to avoid endangering cyclists/cars (the \"Dutch reach\" technique)","nothing in particular","only pedestrians in front of the car","only be careful in the rain"]'::jsonb,
 'den rückwärtigen Verkehr achten, um Radfahrer/Autos nicht zu gefährden ("Holländischer Griff")',
 'traffic approaching from behind, to avoid endangering cyclists/cars (the "Dutch reach" technique)',
 NULL, NULL, 98)

ON CONFLICT (license_class, order_index) DO NOTHING;
