-- ============================================================
-- DeutschPilot – Driving Theory (Klasse B) batch 2, 24 more questions
-- Same rules as batch 1: original prep questions on well-established
-- traffic-law topics, not verbatim official Fragenkatalog content.
-- ============================================================

INSERT INTO public.driving_theory_questions
  (license_class, category, question_de, question_en, options_de, options_en, correct_answer_de, correct_answer_en, explanation_de, explanation_en, order_index)
VALUES

-- Überholen
('B','Überholen',
 'Vor dem Überholen musst du...',
 'Before overtaking, you must...',
 '["den Verkehr hinter und vor dir prüfen und den Blinker setzen","nur nach vorne schauen","sofort beschleunigen","hupen und überholen"]'::jsonb,
 '["check traffic behind and ahead and signal","only look forward","accelerate immediately","honk and overtake"]'::jsonb,
 'den Verkehr hinter und vor dir prüfen und den Blinker setzen',
 'check traffic behind and ahead and signal',
 NULL, NULL, 31),

('B','Überholen',
 'Ein durchgezogener weißer Mittelstreifen bedeutet...',
 'A solid white center line means...',
 '["Überholen und Überfahren ist verboten","Überholen ist immer erlaubt","nur nachts verboten","nur für LKW verboten"]'::jsonb,
 '["overtaking and crossing the line is prohibited","overtaking is always allowed","only prohibited at night","only prohibited for trucks"]'::jsonb,
 'Überholen und Überfahren ist verboten',
 'overtaking and crossing the line is prohibited',
 NULL, NULL, 32),

('B','Überholen',
 'Das Überholverbot-Schild (zwei Autos, eines rot, eines schwarz, im Kreis) hebt sich auf durch...',
 'The no-overtaking sign is cancelled by...',
 '["ein Ende-des-Verbots-Schild oder eine neue Kreuzung/Ortstafel","gar nichts, es gilt für immer","Blinken","Hupen"]'::jsonb,
 '["an end-of-restriction sign, or a new junction/place-name sign","nothing, it applies forever","using your indicator","honking"]'::jsonb,
 'ein Ende-des-Verbots-Schild oder eine neue Kreuzung/Ortstafel',
 'an end-of-restriction sign, or a new junction/place-name sign',
 NULL, NULL, 33),

('B','Überholen',
 'Auf welcher Seite wird in Deutschland normalerweise überholt?',
 'On which side do you normally overtake in Germany?',
 '["links","rechts","beliebig","nur mit Blinker rechts"]'::jsonb,
 '["on the left","on the right","either side","only on the right, with indicator"]'::jsonb,
 'links','on the left',
 'Rechtsüberholen ist auf Landstraßen und Autobahnen grundsätzlich verboten (außer im zähfließenden Kolonnenverkehr).',
 'Overtaking on the right is generally prohibited on rural roads and motorways (except in slow-moving lane traffic).',
 34),

-- Parken & Halten
('B','Parken & Halten',
 'Parken ist im Bereich vor Feuerwehrzufahrten und Kreuzungen (ohne Beschilderung)...',
 'Parking near fire-brigade access points and intersections (without signage)...',
 '["innerhalb bestimmter Mindestabstände verboten","überall erlaubt","nur nachts verboten","nur für Motorräder verboten"]'::jsonb,
 '["prohibited within certain minimum distances","allowed everywhere","only prohibited at night","only prohibited for motorcycles"]'::jsonb,
 'innerhalb bestimmter Mindestabstände verboten',
 'prohibited within certain minimum distances',
 NULL, NULL, 35),

('B','Parken & Halten',
 'Der Unterschied zwischen "Halten" und "Parken" ist...',
 'The difference between "stopping" and "parking" is...',
 '["Halten ist ein kurzer Stopp (z. B. Ein-/Aussteigen), Parken ist ein Verlassen des Fahrzeugs länger als 3 Minuten","es gibt keinen Unterschied","Halten ist nur nachts erlaubt","Parken ist immer kostenlos"]'::jsonb,
 '["Stopping is brief (e.g. letting someone in/out), parking means leaving the vehicle for more than 3 minutes","there is no difference","stopping is only allowed at night","parking is always free"]'::jsonb,
 'Halten ist ein kurzer Stopp (z. B. Ein-/Aussteigen), Parken ist ein Verlassen des Fahrzeugs länger als 3 Minuten',
 'Stopping is brief (e.g. letting someone in/out), parking means leaving the vehicle for more than 3 minutes',
 NULL, NULL, 36),

('B','Parken & Halten',
 'Auf einem Behindertenparkplatz darfst du...',
 'On a disabled parking space, you may...',
 '["nur mit gültigem Schwerbehindertenausweis parken","immer parken","nur nachts parken","nur mit Warnblinklicht parken"]'::jsonb,
 '["only park with a valid disability parking permit","always park","only park at night","only park with hazard lights on"]'::jsonb,
 'nur mit gültigem Schwerbehindertenausweis parken',
 'only park with a valid disability parking permit',
 NULL, NULL, 37),

('B','Parken & Halten',
 'Beim Ausparken/Einparken hast du gegenüber dem fließenden Verkehr...',
 'When pulling out of or into a parking space, relative to moving traffic you...',
 '["grundsätzlich keine Vorfahrt — du musst besonders vorsichtig sein","immer Vorfahrt","Vorfahrt nur bei Tageslicht","keine besondere Pflicht"]'::jsonb,
 '["generally have no right of way — you must be especially careful","always have the right of way","have the right of way only in daylight","have no special obligation"]'::jsonb,
 'grundsätzlich keine Vorfahrt — du musst besonders vorsichtig sein',
 'generally have no right of way — you must be especially careful',
 NULL, NULL, 38),

-- Umweltzone & Umwelt
('B','Umwelt & Umweltzone',
 'Eine grüne Umweltplakette benötigst du, um...',
 'You need a green environmental sticker in order to...',
 '["in eine Umweltzone (z. B. Innenstadt) einfahren zu dürfen","auf der Autobahn zu fahren","zu parken","zu tanken"]'::jsonb,
 '["be allowed to enter a low-emission zone (e.g. a city center)","drive on the Autobahn","park","refuel"]'::jsonb,
 'in eine Umweltzone (z. B. Innenstadt) einfahren zu dürfen',
 'be allowed to enter a low-emission zone (e.g. a city center)',
 NULL, NULL, 39),

('B','Umwelt & Umweltzone',
 'Fährt man ohne gültige Plakette in eine Umweltzone, riskiert man...',
 'Driving into a low-emission zone without a valid sticker risks...',
 '["ein Bußgeld","nur eine Verwarnung ohne Kosten","gar nichts","einen Punkt in Flensburg garantiert"]'::jsonb,
 '["a fine","only a warning with no cost","nothing at all","an automatic point on your license"]'::jsonb,
 'ein Bußgeld','a fine',
 NULL, NULL, 40),

('B','Umwelt & Umweltzone',
 'Unnötiges Motor-Laufenlassen im Stand (z. B. beim Warten) ist in Deutschland...',
 'Unnecessarily letting the engine idle while stationary (e.g. while waiting) is in Germany...',
 '["verboten (Umweltschutz und Lärmvermeidung)","ausdrücklich erlaubt","nur im Winter verboten","nur nachts verboten"]'::jsonb,
 '["prohibited (for environmental and noise reasons)","explicitly allowed","only prohibited in winter","only prohibited at night"]'::jsonb,
 'verboten (Umweltschutz und Lärmvermeidung)',
 'prohibited (for environmental and noise reasons)',
 NULL, NULL, 41),

-- Fußgänger & Radfahrer
('B','Fußgänger & Radfahrer',
 'An einem Zebrastreifen (Fußgängerüberweg) müssen Autofahrer...',
 'At a zebra crossing, drivers must...',
 '["Fußgängern, die erkennbar überqueren wollen, das Überqueren ermöglichen","nur langsamer fahren","hupen, um Fußgänger zu warnen","Vorfahrt haben"]'::jsonb,
 '["allow pedestrians who clearly want to cross to do so","just slow down","honk to warn pedestrians","have the right of way"]'::jsonb,
 'Fußgängern, die erkennbar überqueren wollen, das Überqueren ermöglichen',
 'allow pedestrians who clearly want to cross to do so',
 NULL, NULL, 42),

('B','Fußgänger & Radfahrer',
 'Beim Rechtsabbiegen musst du besonders achten auf...',
 'When turning right, you must pay special attention to...',
 '["Radfahrer und Fußgänger, die geradeaus weiterfahren/-gehen wollen","nur den Gegenverkehr","nur Ampeln","gar nichts Besonderes"]'::jsonb,
 '["cyclists and pedestrians continuing straight ahead","only oncoming traffic","only traffic lights","nothing in particular"]'::jsonb,
 'Radfahrer und Fußgänger, die geradeaus weiterfahren/-gehen wollen',
 'cyclists and pedestrians continuing straight ahead',
 NULL, NULL, 43),

('B','Fußgänger & Radfahrer',
 'Beim Überholen von Radfahrern innerorts solltest du einen Mindestabstand von...',
 'When overtaking cyclists within city limits, you should keep a minimum distance of...',
 '["mindestens 1,5 Metern","keinen besonderen Abstand","30 Zentimetern","5 Metern"]'::jsonb,
 '["at least 1.5 meters","no particular distance","30 centimeters","5 meters"]'::jsonb,
 'mindestens 1,5 Metern','at least 1.5 meters',
 'Außerorts wird sogar ein Mindestabstand von 2 Metern empfohlen/vorgeschrieben.',
 'Outside built-up areas, a minimum distance of even 2 meters is recommended/required.',
 44),

('B','Fußgänger & Radfahrer',
 'Ein Schulbus mit eingeschaltetem Warnblinklicht bedeutet, dass du...',
 'A school bus with hazard lights flashing means you should...',
 '["besonders vorsichtig fahren und mit ein-/aussteigenden Kindern rechnen musst","sofort überholen darfst","hupen musst","keine besondere Vorsicht walten lassen musst"]'::jsonb,
 '["drive with extra caution and expect children getting on/off","overtake immediately","honk","not need any special caution"]'::jsonb,
 'besonders vorsichtig fahren und mit ein-/aussteigenden Kindern rechnen musst',
 'drive with extra caution and expect children getting on/off',
 NULL, NULL, 45),

-- Autobahn-Verhalten
('B','Autobahn-Verhalten',
 'Auf der Autobahn ist Wenden, Rückwärtsfahren und der Verkehr in Gegenrichtung...',
 'On the Autobahn, U-turns, reversing, and driving against the flow of traffic are...',
 '["grundsätzlich verboten","erlaubt bei wenig Verkehr","nur nachts verboten","nur bei Stau erlaubt"]'::jsonb,
 '["generally prohibited","allowed when traffic is light","only prohibited at night","only allowed during a traffic jam"]'::jsonb,
 'grundsätzlich verboten','generally prohibited',
 NULL, NULL, 46),

('B','Autobahn-Verhalten',
 'Bildet sich auf der Autobahn ein Stau, musst du eine Rettungsgasse bilden...',
 'If traffic on the Autobahn comes to a stop, you must form an emergency corridor...',
 '["sobald der Verkehr steht oder sich nur noch im Schritttempo bewegt","erst wenn die Polizei durchfährt","nur bei Regen","nie, das ist freiwillig"]'::jsonb,
 '["as soon as traffic stops or only crawls forward","only once police are driving through","only in rain","never, it is voluntary"]'::jsonb,
 'sobald der Verkehr steht oder sich nur noch im Schritttempo bewegt',
 'as soon as traffic stops or only crawls forward',
 'Die Rettungsgasse wird zwischen dem äußersten linken und dem daneben liegenden Fahrstreifen gebildet.',
 'The emergency corridor is formed between the leftmost lane and the lane next to it.',
 47),

('B','Autobahn-Verhalten',
 'Bei einer Panne auf der Autobahn solltest du zuerst...',
 'In case of a breakdown on the Autobahn, you should first...',
 '["Warnblinklicht einschalten und, wenn möglich, den Seitenstreifen anfahren","sofort aussteigen und auf der Fahrbahn stehen bleiben","weiterfahren, bis der Motor ausgeht","hupen und warten"]'::jsonb,
 '["turn on hazard lights and, if possible, pull onto the hard shoulder","get out immediately and stand on the road","keep driving until the engine dies","honk and wait"]'::jsonb,
 'Warnblinklicht einschalten und, wenn möglich, den Seitenstreifen anfahren',
 'turn on hazard lights and, if possible, pull onto the hard shoulder',
 NULL, NULL, 48),

('B','Autobahn-Verhalten',
 'Der linke Fahrstreifen auf der Autobahn ist...',
 'The left lane on the Autobahn is...',
 '["zum Überholen da, nicht zum dauerhaften Fahren","zum dauerhaften Fahren gedacht","nur für LKW reserviert","nur bei Nacht nutzbar"]'::jsonb,
 '["for overtaking, not for continuous driving","meant for continuous driving","reserved only for trucks","only usable at night"]'::jsonb,
 'zum Überholen da, nicht zum dauerhaften Fahren',
 'for overtaking, not for continuous driving',
 NULL, NULL, 49),

-- Ampel & Kreuzungen
('B','Ampel & Kreuzungen',
 'Gelbes Ampellicht bedeutet...',
 'A yellow traffic light means...',
 '["anhalten, wenn du noch gefahrlos anhalten kannst","freie Fahrt, schneller fahren","sofort stehen bleiben, egal wo","nur für Fußgänger relevant"]'::jsonb,
 '["stop if you can still do so safely","proceed, speed up","stop immediately regardless of position","only relevant for pedestrians"]'::jsonb,
 'anhalten, wenn du noch gefahrlos anhalten kannst',
 'stop if you can still do so safely',
 NULL, NULL, 50),

('B','Ampel & Kreuzungen',
 'Ein grüner Pfeil an einer roten Ampel (auf einem separaten schwarzen Schild) bedeutet...',
 'A green arrow next to a red light (on a separate black sign) means...',
 '["Rechtsabbiegen ist nach vollständigem Anhalten und Beachten des Verkehrs erlaubt","Rechtsabbiegen ist ohne Anhalten immer erlaubt","der Pfeil gilt nur für Busse","es besteht Anhaltepflicht ohne Ausnahme"]'::jsonb,
 '["turning right is allowed after a complete stop and checking traffic","turning right is always allowed without stopping","the arrow only applies to buses","stopping is required with no exception"]'::jsonb,
 'Rechtsabbiegen ist nach vollständigem Anhalten und Beachten des Verkehrs erlaubt',
 'turning right is allowed after a complete stop and checking traffic',
 NULL, NULL, 51),

('B','Ampel & Kreuzungen',
 'An einer Kreuzung mit ausgefallener Ampel gilt...',
 'At an intersection where the traffic light has failed, the rule is...',
 '["rechts vor links, wie bei einer unbeschilderten Kreuzung","freie Fahrt für alle","man muss immer anhalten und warten","nur Polizei darf durchfahren"]'::jsonb,
 '["right before left, as at an unmarked intersection","free passage for everyone","you must always stop and wait indefinitely","only police may pass through"]'::jsonb,
 'rechts vor links, wie bei einer unbeschilderten Kreuzung',
 'right before left, as at an unmarked intersection',
 NULL, NULL, 52),

('B','Ampel & Kreuzungen',
 'Ein Verkehrspolizist, der den Verkehr regelt, hat gegenüber einer Ampel...',
 'A traffic police officer directing traffic, compared to traffic lights, has...',
 '["Vorrang — seine Anweisungen gelten über der Ampel","keine besondere Bedeutung","Vorrang nur bei Rot","Vorrang nur nachts"]'::jsonb,
 '["priority — their instructions override the traffic lights","no particular significance","priority only at red lights","priority only at night"]'::jsonb,
 'Vorrang — seine Anweisungen gelten über der Ampel',
 'priority — their instructions override the traffic lights',
 NULL, NULL, 53),

('B','Ampel & Kreuzungen',
 'Beim Linksabbiegen an einer Kreuzung ohne Ampel-Pfeil musst du...',
 'When turning left at an intersection without a dedicated arrow signal, you must...',
 '["dem entgegenkommenden Verkehr Vorfahrt gewähren","sofort abbiegen, sobald grün ist","hupen, um Platz zu bekommen","nur auf Fußgänger achten"]'::jsonb,
 '["yield to oncoming traffic","turn immediately as soon as the light is green","honk to get space","only watch for pedestrians"]'::jsonb,
 'dem entgegenkommenden Verkehr Vorfahrt gewähren',
 'yield to oncoming traffic',
 NULL, NULL, 54)

ON CONFLICT (license_class, order_index) DO NOTHING;
